### ISSUE TITLE
'PosixPath' object has no attribute 'write'

### ISSUE THREAD

**Issue by hmam789xp** [chuangzhu/oidv6-to-voc#1]
Hello @chuangzhu , 

Thanks for this tool. But I have an issue with running it on Colab. it gives me the following error 
'PosixPath' object has no attribute 'write'

I would really appreciate your help

Thanks

**Comment by chuangzhu** [comment]
I tried to run it on Colab and no errors occurred:

https://gist.github.com/chuangzhu/654067d7ad82e4d7bc580770f18fccbf

Could you show me how did you run it?

**Comment by hmam789xp** [comment]
!python3.6 -m oidv6_to_voc OpenImages/boxes/oidv6-train-annotations-bbox.csv -d 'class-descriptions-boxable.csv' --imgd 'OpenImages/train/traffic_light' -o OpenImages/train/newLabel


Output:
Getting image ids...
Reading annotation CSV...
Generating VOC XMLs...
Traceback (most recent call last):
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 789, in _get_writer
    write = file_or_filename.write
AttributeError: 'PosixPath' object has no attribute 'write'

During handling of the above exception, another exception occurred:

**Comment by chuangzhu** [comment]
Sorry but I failed reproducing the issue. There is a try-except statement in `/usr/lib/python3.6/xml/etree/ElementTree.py` in Python 3.6.9, which is the version Google Colab's using, so there shouldn't be any change for the error to throw:

```python
    try:
        write = file_or_filename.write
    except AttributeError:
        # file_or_filename is a file name
```

Did you change the version of Python, or did some modifications to the Python you use?

**Comment by hmam789xp** [comment]
I did upgrade python to 3.7 to install oidv6 as i cound't do it with the 3.6.8. 
but when I run you code i use 3.6.9 so I am not sure whats the issue. Any suggestion to get this solved please ?

**Comment by chuangzhu** [comment]
Could you provide a minimal Jupyter Notebook to reproduce the error? You can share the Jupyter Notebook via `File > Save a copy as a GitHub Gist`

![Screenshot_20201229_112553](https://user-images.githubusercontent.com/31200881/103256635-f05f5b00-49c8-11eb-9220-85c037ce5f27.png)

**Comment by hmam789xp** [comment]
Here is the link for the GitHub Gist:

https://gist.github.com/hmam789xp/ed5b8f1a967d359aa65dbde952eddc9a

**Comment by chuangzhu** [comment]
@hmam789xp In your case, run:

```bash
!mkdir -p OpenImages/train/newLabel
```

I'll add the functionality to automatically create the output directory in the next version.

**Comment by hmam789xp** [comment]
THANK YOU very much it is working now.
